### ISSUE TITLE
Finish HTML and CSS for first page

### ISSUE THREAD

**Issue by Vannasaur** [Marcos-Wang/Project-1-JVM#2]

**Comment by James-Brainard** [comment]
Make buttons have opacity, most other elements for the first page are done. 
Need to add additional CSS styling to finalize page.
Finalize buttons to line up with location details directly below. May conflict with smaller screens, check on this.

**Comment by James-Brainard** [comment]
Helvetica for the text & bold for the buttons.

**Comment by James-Brainard** [comment]
Marcos & James finished the html 1st and 2nd page. Still need basic styling to add finishing touches.
